apiVersion: apps/v1
kind: Deployment
metadata:
  name: ponger-micro-grpc
  labels:
    app: ponger-micro-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ponger-micro-grpc
  template:
    metadata:
      labels:
        app: ponger-micro-grpc
    spec:
      containers:
        - name: ponger-micro-grpc
          image: gomicro-pinger-image
          args: [ "ponger", "micro-grpc", "--port=6066" ]
          ports:
            - containerPort: 6066
---
apiVersion: v1
kind: Service
metadata:
  name: ponger-micro-grpc
spec:
  selector:
    app: ponger-micro-grpc
  ports:
    - protocol: TCP
      port: 6066
      targetPort: 6066
